openapi: 3.1.1
info:
  title: Generated API
  version: 1.0.0
  contact:
    name: Narinder Kaur
    url: http://dummy.com
    email: dummy@hotmail.com
servers:
- description: Localhost server
  url: http://localhost:31002/